# The config recipe.
# https://rasa.com/docs/rasa/model-configuration/
recipe: default.v1

# Configuration for Rasa NLU.
# https://rasa.com/docs/rasa/nlu/components/
language: es

pipeline:
   - name: SpacyNLP
     model: es_core_news_lg
     case_sensitive: false
   - name: SpacyTokenizer
   - name: SpacyEntityExtractor
     # para extraer los nombres de usuarios (nombres propios)
     dimensions: ["PER"]
   - name: DucklingEntityExtractor
     dimensions: ["time", "number", "url", "duration"]
      # para extraer todas las entidades pre-entrenadas en Duckling, se debe dejar el parámetro "dimensions" sin especificar
     url: http://0.0.0.0:8000
     # para probar, correr con el comando "docker run -p 8000:8000 rasa/duckling"
     locale: es_CL
     timezone: America/Santiago
     timeout: 5
   - name: LexicalSyntacticFeaturizer
   - name: RegexFeaturizer
   - name: RegexEntityExtractor
   - name: CountVectorsFeaturizer
   - name: DIETClassifier
     epochs: 100
     constrain_similarities: true
   - name: EntitySynonymMapper
   - name: ResponseSelector
     epochs: 100
   - name: FallbackClassifier
     threshold: 0.8
     ambiguity_threshold: 0.1

policies:
   - name: MemoizationPolicy
   - name: RulePolicy
   - name: UnexpecTEDIntentPolicy
     max_history: 5
     epochs: 100
   - name: TEDPolicy
     max_history: 5
     epochs: 100
     constrain_similarities: true